version: '3.9'


services:
  backend:
    build: ./backend
    expose:
      - "8000:8000"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - ".env"
    expose:
      - "5000:5000"
    ports:
      - "5000:5000"
    depends_on:
      - backend
  
  bot:
    build: ./bot
    env_file:
      - ".env"
    depends_on:
      - backend
    
