version: '3.9'


services:
  backend:
    build: ./backend
    expose:
      - "8000:8000"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    expose:
      - "5000:5000"
    ports:
      - "5000:5000"
    
    depends_on:
      - backend
    
